export type PageTemplate = {
  id: string;
  name: string;
  icon: string;
  title: string;
  description?: string;
  content: unknown[];
};

const text = (s: string) => [{ type: "text", text: s, styles: {} }];

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    id: "meeting",
    name: "Meeting notes",
    icon: "📝",
    title: "Meeting notes",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Meeting notes") },
      { type: "paragraph", content: text("Date: ") },
      { type: "paragraph", content: text("Attendees: ") },
      { type: "heading", props: { level: 2 }, content: text("Agenda") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Discussion") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Action items") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
    ],
  },
  {
    id: "project",
    name: "Project brief",
    icon: "🚀",
    title: "Project brief",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Project brief") },
      { type: "callout", props: { emoji: "🎯", color: "yellow" }, content: text("Goal of this project") },
      { type: "heading", props: { level: 2 }, content: text("Context") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Scope") },
      { type: "bulletListItem", content: text("In scope: ") },
      { type: "bulletListItem", content: text("Out of scope: ") },
      { type: "heading", props: { level: 2 }, content: text("Milestones") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Owners") },
      { type: "paragraph", content: text("") },
    ],
  },
  {
    id: "reading",
    name: "Reading list",
    icon: "📚",
    title: "Reading list",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Reading list") },
      { type: "paragraph", content: text("Books, articles, papers I want to read.") },
      { type: "heading", props: { level: 2 }, content: text("Now reading") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("To read") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Done") },
      { type: "bulletListItem", content: text("") },
    ],
  },
  {
    id: "todo",
    name: "Daily to-do",
    icon: "✅",
    title: "Daily to-do",
    description: "A short checklist for the day, plus a notes section.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Today") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Notes") },
      { type: "paragraph", content: text("") },
    ],
  },
  {
    id: "weekly-review",
    name: "Weekly review",
    icon: "📅",
    title: "Week of …",
    description: "Wins, lessons, and next-week priorities.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Weekly review") },
      { type: "heading", props: { level: 2 }, content: text("Wins") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Lessons / challenges") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Next week priorities") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
    ],
  },
  {
    id: "okr",
    name: "OKR planning",
    icon: "🎯",
    title: "OKRs",
    description: "Quarterly objectives with measurable key results.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("OKRs") },
      { type: "callout", props: { emoji: "🎯", color: "blue" }, content: text("Quarter / Year goals") },
      { type: "heading", props: { level: 2 }, content: text("Objective 1") },
      { type: "paragraph", content: text("KR 1: ") },
      { type: "paragraph", content: text("KR 2: ") },
      { type: "paragraph", content: text("KR 3: ") },
      { type: "heading", props: { level: 2 }, content: text("Objective 2") },
      { type: "paragraph", content: text("KR 1: ") },
    ],
  },
  {
    id: "1on1",
    name: "1:1 notes",
    icon: "🗣",
    title: "1:1 with …",
    description: "Recurring agenda + parking lot for ongoing 1:1s.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("1:1 notes") },
      { type: "paragraph", content: text("Date: ") },
      { type: "heading", props: { level: 2 }, content: text("Agenda") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Updates") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Action items") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Parking lot") },
      { type: "bulletListItem", content: text("") },
    ],
  },
  {
    id: "decision",
    name: "Decision log",
    icon: "⚖️",
    title: "Decision: …",
    description: "Records the context, options considered, and the call.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Decision: …") },
      { type: "paragraph", content: text("Date: ") },
      { type: "paragraph", content: text("Driver: ") },
      { type: "heading", props: { level: 2 }, content: text("Context") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Options") },
      { type: "bulletListItem", content: text("A: ") },
      { type: "bulletListItem", content: text("B: ") },
      { type: "heading", props: { level: 2 }, content: text("Decision") },
      { type: "callout", props: { emoji: "✅", color: "green" }, content: text("Chosen option + why") },
      { type: "heading", props: { level: 2 }, content: text("Consequences") },
      { type: "paragraph", content: text("") },
    ],
  },
  {
    id: "doc",
    name: "Design doc",
    icon: "📐",
    title: "Design: …",
    description: "Lightweight technical design doc skeleton.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Design: …") },
      { type: "paragraph", content: text("Author: ") },
      { type: "paragraph", content: text("Status: Draft") },
      { type: "heading", props: { level: 2 }, content: text("Problem") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Proposal") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Alternatives") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Risks") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Open questions") },
      { type: "bulletListItem", content: text("") },
    ],
  },
  {
    id: "journal",
    name: "Daily journal",
    icon: "📓",
    title: "Journal · …",
    description: "Mood, highlight, gratitude, tomorrow.",
    content: [
      { type: "heading", props: { level: 1 }, content: text("Journal") },
      { type: "paragraph", content: text("Mood: ") },
      { type: "heading", props: { level: 2 }, content: text("Highlight of the day") },
      { type: "paragraph", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Grateful for") },
      { type: "bulletListItem", content: text("") },
      { type: "heading", props: { level: 2 }, content: text("Tomorrow") },
      { type: "checkListItem", props: { checked: false }, content: text("") },
    ],
  },
];
